//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cache-max-size-policy.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="cache-max-size-policy">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ENTRY_COUNT"/>
 *     &lt;enumeration value="USED_NATIVE_MEMORY_SIZE"/>
 *     &lt;enumeration value="USED_NATIVE_MEMORY_PERCENTAGE"/>
 *     &lt;enumeration value="FREE_NATIVE_MEMORY_SIZE"/>
 *     &lt;enumeration value="FREE_NATIVE_MEMORY_PERCENTAGE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cache-max-size-policy")
@XmlEnum
public enum CacheMaxSizePolicy {

    ENTRY_COUNT,
    USED_NATIVE_MEMORY_SIZE,
    USED_NATIVE_MEMORY_PERCENTAGE,
    FREE_NATIVE_MEMORY_SIZE,
    FREE_NATIVE_MEMORY_PERCENTAGE;

    public String value() {
        return name();
    }

    public static CacheMaxSizePolicy fromValue(String v) {
        return valueOf(v);
    }

}
