//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cache complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cache">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="key-type" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="class-name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="value-type" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="class-name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="statistics-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="management-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="read-through" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="write-through" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="cache-loader-factory" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="class-name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cache-writer-factory" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="class-name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="expiry-policy-factory" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="class-name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cache-entry-listeners" type="{http://www.hazelcast.com/schema/config}cache-entry-listeners" minOccurs="0"/>
 *         &lt;element name="in-memory-format" type="{http://www.hazelcast.com/schema/config}in-memory-format" minOccurs="0"/>
 *         &lt;element name="backup-count" type="{http://www.hazelcast.com/schema/config}backup-count" minOccurs="0"/>
 *         &lt;element name="async-backup-count" type="{http://www.hazelcast.com/schema/config}backup-count" minOccurs="0"/>
 *         &lt;element name="eviction" type="{http://www.hazelcast.com/schema/config}cache-eviction" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cache", propOrder = {
    "keyType",
    "valueType",
    "statisticsEnabled",
    "managementEnabled",
    "readThrough",
    "writeThrough",
    "cacheLoaderFactory",
    "cacheWriterFactory",
    "expiryPolicyFactory",
    "cacheEntryListeners",
    "inMemoryFormat",
    "backupCount",
    "asyncBackupCount",
    "eviction"
})
public class Cache {

    @XmlElement(name = "key-type")
    protected Cache.KeyType keyType;
    @XmlElement(name = "value-type")
    protected Cache.ValueType valueType;
    @XmlElement(name = "statistics-enabled", defaultValue = "false")
    protected Boolean statisticsEnabled;
    @XmlElement(name = "management-enabled", defaultValue = "false")
    protected Boolean managementEnabled;
    @XmlElement(name = "read-through", defaultValue = "false")
    protected Boolean readThrough;
    @XmlElement(name = "write-through", defaultValue = "false")
    protected Boolean writeThrough;
    @XmlElement(name = "cache-loader-factory")
    protected Cache.CacheLoaderFactory cacheLoaderFactory;
    @XmlElement(name = "cache-writer-factory")
    protected Cache.CacheWriterFactory cacheWriterFactory;
    @XmlElement(name = "expiry-policy-factory")
    protected Cache.ExpiryPolicyFactory expiryPolicyFactory;
    @XmlElement(name = "cache-entry-listeners")
    protected CacheEntryListeners cacheEntryListeners;
    @XmlElement(name = "in-memory-format", defaultValue = "BINARY")
    @XmlSchemaType(name = "string")
    protected InMemoryFormat inMemoryFormat;
    @XmlElement(name = "backup-count", defaultValue = "0")
    protected Byte backupCount;
    @XmlElement(name = "async-backup-count", defaultValue = "1")
    protected Byte asyncBackupCount;
    protected CacheEviction eviction;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the keyType property.
     * 
     * @return
     *     possible object is
     *     {@link Cache.KeyType }
     *     
     */
    public Cache.KeyType getKeyType() {
        return keyType;
    }

    /**
     * Sets the value of the keyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cache.KeyType }
     *     
     */
    public void setKeyType(Cache.KeyType value) {
        this.keyType = value;
    }

    /**
     * Gets the value of the valueType property.
     * 
     * @return
     *     possible object is
     *     {@link Cache.ValueType }
     *     
     */
    public Cache.ValueType getValueType() {
        return valueType;
    }

    /**
     * Sets the value of the valueType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cache.ValueType }
     *     
     */
    public void setValueType(Cache.ValueType value) {
        this.valueType = value;
    }

    /**
     * Gets the value of the statisticsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStatisticsEnabled() {
        return statisticsEnabled;
    }

    /**
     * Sets the value of the statisticsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStatisticsEnabled(Boolean value) {
        this.statisticsEnabled = value;
    }

    /**
     * Gets the value of the managementEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isManagementEnabled() {
        return managementEnabled;
    }

    /**
     * Sets the value of the managementEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setManagementEnabled(Boolean value) {
        this.managementEnabled = value;
    }

    /**
     * Gets the value of the readThrough property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReadThrough() {
        return readThrough;
    }

    /**
     * Sets the value of the readThrough property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReadThrough(Boolean value) {
        this.readThrough = value;
    }

    /**
     * Gets the value of the writeThrough property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWriteThrough() {
        return writeThrough;
    }

    /**
     * Sets the value of the writeThrough property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWriteThrough(Boolean value) {
        this.writeThrough = value;
    }

    /**
     * Gets the value of the cacheLoaderFactory property.
     * 
     * @return
     *     possible object is
     *     {@link Cache.CacheLoaderFactory }
     *     
     */
    public Cache.CacheLoaderFactory getCacheLoaderFactory() {
        return cacheLoaderFactory;
    }

    /**
     * Sets the value of the cacheLoaderFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cache.CacheLoaderFactory }
     *     
     */
    public void setCacheLoaderFactory(Cache.CacheLoaderFactory value) {
        this.cacheLoaderFactory = value;
    }

    /**
     * Gets the value of the cacheWriterFactory property.
     * 
     * @return
     *     possible object is
     *     {@link Cache.CacheWriterFactory }
     *     
     */
    public Cache.CacheWriterFactory getCacheWriterFactory() {
        return cacheWriterFactory;
    }

    /**
     * Sets the value of the cacheWriterFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cache.CacheWriterFactory }
     *     
     */
    public void setCacheWriterFactory(Cache.CacheWriterFactory value) {
        this.cacheWriterFactory = value;
    }

    /**
     * Gets the value of the expiryPolicyFactory property.
     * 
     * @return
     *     possible object is
     *     {@link Cache.ExpiryPolicyFactory }
     *     
     */
    public Cache.ExpiryPolicyFactory getExpiryPolicyFactory() {
        return expiryPolicyFactory;
    }

    /**
     * Sets the value of the expiryPolicyFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cache.ExpiryPolicyFactory }
     *     
     */
    public void setExpiryPolicyFactory(Cache.ExpiryPolicyFactory value) {
        this.expiryPolicyFactory = value;
    }

    /**
     * Gets the value of the cacheEntryListeners property.
     * 
     * @return
     *     possible object is
     *     {@link CacheEntryListeners }
     *     
     */
    public CacheEntryListeners getCacheEntryListeners() {
        return cacheEntryListeners;
    }

    /**
     * Sets the value of the cacheEntryListeners property.
     * 
     * @param value
     *     allowed object is
     *     {@link CacheEntryListeners }
     *     
     */
    public void setCacheEntryListeners(CacheEntryListeners value) {
        this.cacheEntryListeners = value;
    }

    /**
     * Gets the value of the inMemoryFormat property.
     * 
     * @return
     *     possible object is
     *     {@link InMemoryFormat }
     *     
     */
    public InMemoryFormat getInMemoryFormat() {
        return inMemoryFormat;
    }

    /**
     * Sets the value of the inMemoryFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link InMemoryFormat }
     *     
     */
    public void setInMemoryFormat(InMemoryFormat value) {
        this.inMemoryFormat = value;
    }

    /**
     * Gets the value of the backupCount property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getBackupCount() {
        return backupCount;
    }

    /**
     * Sets the value of the backupCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setBackupCount(Byte value) {
        this.backupCount = value;
    }

    /**
     * Gets the value of the asyncBackupCount property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getAsyncBackupCount() {
        return asyncBackupCount;
    }

    /**
     * Sets the value of the asyncBackupCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setAsyncBackupCount(Byte value) {
        this.asyncBackupCount = value;
    }

    /**
     * Gets the value of the eviction property.
     * 
     * @return
     *     possible object is
     *     {@link CacheEviction }
     *     
     */
    public CacheEviction getEviction() {
        return eviction;
    }

    /**
     * Sets the value of the eviction property.
     * 
     * @param value
     *     allowed object is
     *     {@link CacheEviction }
     *     
     */
    public void setEviction(CacheEviction value) {
        this.eviction = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * 
     *                             Defines the cache loader factory class name.
     *                         
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="class-name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CacheLoaderFactory {

        @XmlAttribute(name = "class-name", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String className;

        /**
         * Gets the value of the className property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClassName() {
            return className;
        }

        /**
         * Sets the value of the className property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClassName(String value) {
            this.className = value;
        }

    }


    /**
     * 
     *                             Defines the cache writer factory class name.
     *                         
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="class-name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CacheWriterFactory {

        @XmlAttribute(name = "class-name", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String className;

        /**
         * Gets the value of the className property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClassName() {
            return className;
        }

        /**
         * Sets the value of the className property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClassName(String value) {
            this.className = value;
        }

    }


    /**
     * 
     *                             Defines the expiry policy factory class name.
     *                         
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="class-name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ExpiryPolicyFactory {

        @XmlAttribute(name = "class-name", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String className;

        /**
         * Gets the value of the className property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClassName() {
            return className;
        }

        /**
         * Sets the value of the className property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClassName(String value) {
            this.className = value;
        }

    }


    /**
     * 
     *                             the type of keys provided as full class name
     *                         
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="class-name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class KeyType {

        @XmlAttribute(name = "class-name", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String className;

        /**
         * Gets the value of the className property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClassName() {
            return className;
        }

        /**
         * Sets the value of the className property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClassName(String value) {
            this.className = value;
        }

    }


    /**
     * 
     *                             the type of values provided as full class name
     *                         
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="class-name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ValueType {

        @XmlAttribute(name = "class-name", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String className;

        /**
         * Gets the value of the className property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClassName() {
            return className;
        }

        /**
         * Sets the value of the className property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClassName(String value) {
            this.className = value;
        }

    }

}
