//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cache-entry-listener complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cache-entry-listener">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cache-entry-listener-factory" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="class-name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cache-entry-event-filter-factory" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="class-name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="old-value-required" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="synchronous" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cache-entry-listener", propOrder = {
    "cacheEntryListenerFactory",
    "cacheEntryEventFilterFactory"
})
public class CacheEntryListener {

    @XmlElement(name = "cache-entry-listener-factory")
    protected CacheEntryListener.CacheEntryListenerFactory cacheEntryListenerFactory;
    @XmlElement(name = "cache-entry-event-filter-factory")
    protected CacheEntryListener.CacheEntryEventFilterFactory cacheEntryEventFilterFactory;
    @XmlAttribute(name = "old-value-required")
    protected Boolean oldValueRequired;
    @XmlAttribute(name = "synchronous")
    protected Boolean synchronous;

    /**
     * Gets the value of the cacheEntryListenerFactory property.
     * 
     * @return
     *     possible object is
     *     {@link CacheEntryListener.CacheEntryListenerFactory }
     *     
     */
    public CacheEntryListener.CacheEntryListenerFactory getCacheEntryListenerFactory() {
        return cacheEntryListenerFactory;
    }

    /**
     * Sets the value of the cacheEntryListenerFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link CacheEntryListener.CacheEntryListenerFactory }
     *     
     */
    public void setCacheEntryListenerFactory(CacheEntryListener.CacheEntryListenerFactory value) {
        this.cacheEntryListenerFactory = value;
    }

    /**
     * Gets the value of the cacheEntryEventFilterFactory property.
     * 
     * @return
     *     possible object is
     *     {@link CacheEntryListener.CacheEntryEventFilterFactory }
     *     
     */
    public CacheEntryListener.CacheEntryEventFilterFactory getCacheEntryEventFilterFactory() {
        return cacheEntryEventFilterFactory;
    }

    /**
     * Sets the value of the cacheEntryEventFilterFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link CacheEntryListener.CacheEntryEventFilterFactory }
     *     
     */
    public void setCacheEntryEventFilterFactory(CacheEntryListener.CacheEntryEventFilterFactory value) {
        this.cacheEntryEventFilterFactory = value;
    }

    /**
     * Gets the value of the oldValueRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOldValueRequired() {
        if (oldValueRequired == null) {
            return false;
        } else {
            return oldValueRequired;
        }
    }

    /**
     * Sets the value of the oldValueRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOldValueRequired(Boolean value) {
        this.oldValueRequired = value;
    }

    /**
     * Gets the value of the synchronous property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSynchronous() {
        if (synchronous == null) {
            return false;
        } else {
            return synchronous;
        }
    }

    /**
     * Sets the value of the synchronous property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSynchronous(Boolean value) {
        this.synchronous = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="class-name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CacheEntryEventFilterFactory {

        @XmlAttribute(name = "class-name", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String className;

        /**
         * Gets the value of the className property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClassName() {
            return className;
        }

        /**
         * Sets the value of the className property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClassName(String value) {
            this.className = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="class-name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CacheEntryListenerFactory {

        @XmlAttribute(name = "class-name", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String className;

        /**
         * Gets the value of the className property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClassName() {
            return className;
        }

        /**
         * Sets the value of the className property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClassName(String value) {
            this.className = value;
        }

    }

}
