//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import java.util.ArrayList;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.hazelcast.com/schema/config}import"/>
 *         &lt;element name="group" type="{http://www.hazelcast.com/schema/config}cluster-group" minOccurs="0"/>
 *         &lt;element name="license-key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="management-center" type="{http://www.hazelcast.com/schema/config}management-center" minOccurs="0"/>
 *         &lt;element name="properties" type="{http://www.hazelcast.com/schema/config}properties" minOccurs="0"/>
 *         &lt;element name="wan-replication" type="{http://www.hazelcast.com/schema/config}wan-replication" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="network" type="{http://www.hazelcast.com/schema/config}network" minOccurs="0"/>
 *         &lt;element name="partition-group" type="{http://www.hazelcast.com/schema/config}partition-group" minOccurs="0"/>
 *         &lt;element name="executor-service" type="{http://www.hazelcast.com/schema/config}executor-service" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="queue" type="{http://www.hazelcast.com/schema/config}queue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="map" type="{http://www.hazelcast.com/schema/config}map" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="multimap" type="{http://www.hazelcast.com/schema/config}multimap" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="replicatedmap" type="{http://www.hazelcast.com/schema/config}replicatedmap" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="cache" type="{http://www.hazelcast.com/schema/config}cache" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="list" type="{http://www.hazelcast.com/schema/config}list" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="set" type="{http://www.hazelcast.com/schema/config}set" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="topic" type="{http://www.hazelcast.com/schema/config}topic" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="jobtracker" type="{http://www.hazelcast.com/schema/config}jobtracker" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="semaphore" type="{http://www.hazelcast.com/schema/config}semaphore" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="listeners" type="{http://www.hazelcast.com/schema/config}listeners" minOccurs="0"/>
 *         &lt;element name="serialization" type="{http://www.hazelcast.com/schema/config}serialization" minOccurs="0"/>
 *         &lt;element name="native-memory" type="{http://www.hazelcast.com/schema/config}native-memory" minOccurs="0"/>
 *         &lt;element name="services" type="{http://www.hazelcast.com/schema/config}services" minOccurs="0"/>
 *         &lt;element name="security" type="{http://www.hazelcast.com/schema/config}security" minOccurs="0"/>
 *         &lt;element ref="{http://www.hazelcast.com/schema/config}member-attributes" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" default="default" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "importOrGroupOrLicenseKey"
})
@XmlRootElement(name = "hazelcast")
public class Hazelcast {

    @XmlElements({
        @XmlElement(name = "import", type = Import.class),
        @XmlElement(name = "group", type = ClusterGroup.class),
        @XmlElement(name = "license-key", type = String.class),
        @XmlElement(name = "management-center", type = ManagementCenter.class),
        @XmlElement(name = "properties", type = Properties.class),
        @XmlElement(name = "wan-replication", type = WanReplication.class),
        @XmlElement(name = "network", type = Network.class),
        @XmlElement(name = "partition-group", type = PartitionGroup.class),
        @XmlElement(name = "executor-service", type = ExecutorService.class),
        @XmlElement(name = "queue", type = Queue.class),
        @XmlElement(name = "map", type = Map.class),
        @XmlElement(name = "multimap", type = Multimap.class),
        @XmlElement(name = "replicatedmap", type = Replicatedmap.class),
        @XmlElement(name = "cache", type = Cache.class),
        @XmlElement(name = "list", type = cloud.configs.hazelcast.dynamictemplate.v34.schema.List.class),
        @XmlElement(name = "set", type = Set.class),
        @XmlElement(name = "topic", type = Topic.class),
        @XmlElement(name = "jobtracker", type = Jobtracker.class),
        @XmlElement(name = "semaphore", type = Semaphore.class),
        @XmlElement(name = "listeners", type = Listeners.class),
        @XmlElement(name = "serialization", type = Serialization.class),
        @XmlElement(name = "native-memory", type = NativeMemory.class),
        @XmlElement(name = "services", type = Services.class),
        @XmlElement(name = "security", type = Security.class),
        @XmlElement(name = "member-attributes", type = MemberAttributes.class)
    })
    protected java.util.List<Object> importOrGroupOrLicenseKey;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the importOrGroupOrLicenseKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the importOrGroupOrLicenseKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImportOrGroupOrLicenseKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Import }
     * {@link ClusterGroup }
     * {@link String }
     * {@link ManagementCenter }
     * {@link Properties }
     * {@link WanReplication }
     * {@link Network }
     * {@link PartitionGroup }
     * {@link ExecutorService }
     * {@link Queue }
     * {@link Map }
     * {@link Multimap }
     * {@link Replicatedmap }
     * {@link Cache }
     * {@link com.hazelcast.schema.config.List }
     * {@link Set }
     * {@link Topic }
     * {@link Jobtracker }
     * {@link Semaphore }
     * {@link Listeners }
     * {@link Serialization }
     * {@link NativeMemory }
     * {@link Services }
     * {@link Security }
     * {@link MemberAttributes }
     * 
     * 
     */
    public java.util.List<Object> getImportOrGroupOrLicenseKey() {
        if (importOrGroupOrLicenseKey == null) {
            importOrGroupOrLicenseKey = new ArrayList<Object>();
        }
        return this.importOrGroupOrLicenseKey;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        if (id == null) {
            return "default";
        } else {
            return id;
        }
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
