//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The JobTracker configuration is used to setup behavior of the Hazelcast MapReduce framework.
 *                 Every JobTracker is capable of running multiple map reduce jobs at once and so once configuration
 *                 is meant as a shared resource for all jobs created by the same JobTracker.
 *                 The configuration gives full control over the expected load behavior and thread counts to be used.
 *             
 * 
 * <p>Java class for jobtracker complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="jobtracker">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="max-thread-size" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="queue-size" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="retry-count" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="chunk-size" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="communicate-stats" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="topology-changed-strategy" type="{http://www.hazelcast.com/schema/config}topology-changed-strategy" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "jobtracker", propOrder = {
    "maxThreadSize",
    "queueSize",
    "retryCount",
    "chunkSize",
    "communicateStats",
    "topologyChangedStrategy"
})
public class Jobtracker {

    @XmlElement(name = "max-thread-size", defaultValue = "0")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger maxThreadSize;
    @XmlElement(name = "queue-size", defaultValue = "0")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger queueSize;
    @XmlElement(name = "retry-count", defaultValue = "0")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger retryCount;
    @XmlElement(name = "chunk-size", defaultValue = "1000")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger chunkSize;
    @XmlElement(name = "communicate-stats", defaultValue = "true")
    protected Boolean communicateStats;
    @XmlElement(name = "topology-changed-strategy", defaultValue = "CANCEL_RUNNING_OPERATION")
    @XmlSchemaType(name = "string")
    protected TopologyChangedStrategy topologyChangedStrategy;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the maxThreadSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxThreadSize() {
        return maxThreadSize;
    }

    /**
     * Sets the value of the maxThreadSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxThreadSize(BigInteger value) {
        this.maxThreadSize = value;
    }

    /**
     * Gets the value of the queueSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQueueSize() {
        return queueSize;
    }

    /**
     * Sets the value of the queueSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQueueSize(BigInteger value) {
        this.queueSize = value;
    }

    /**
     * Gets the value of the retryCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRetryCount() {
        return retryCount;
    }

    /**
     * Sets the value of the retryCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRetryCount(BigInteger value) {
        this.retryCount = value;
    }

    /**
     * Gets the value of the chunkSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChunkSize() {
        return chunkSize;
    }

    /**
     * Sets the value of the chunkSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChunkSize(BigInteger value) {
        this.chunkSize = value;
    }

    /**
     * Gets the value of the communicateStats property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCommunicateStats() {
        return communicateStats;
    }

    /**
     * Sets the value of the communicateStats property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCommunicateStats(Boolean value) {
        this.communicateStats = value;
    }

    /**
     * Gets the value of the topologyChangedStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link TopologyChangedStrategy }
     *     
     */
    public TopologyChangedStrategy getTopologyChangedStrategy() {
        return topologyChangedStrategy;
    }

    /**
     * Sets the value of the topologyChangedStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link TopologyChangedStrategy }
     *     
     */
    public void setTopologyChangedStrategy(TopologyChangedStrategy value) {
        this.topologyChangedStrategy = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
