//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for map complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="map">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="in-memory-format" type="{http://www.hazelcast.com/schema/config}in-memory-format" minOccurs="0"/>
 *         &lt;element name="statistics-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="optimize-queries" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="backup-count" type="{http://www.hazelcast.com/schema/config}backup-count" minOccurs="0"/>
 *         &lt;element name="async-backup-count" type="{http://www.hazelcast.com/schema/config}backup-count" minOccurs="0"/>
 *         &lt;element name="time-to-live-seconds" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="max-idle-seconds" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="eviction-policy" type="{http://www.hazelcast.com/schema/config}eviction-policy" minOccurs="0"/>
 *         &lt;element name="max-size" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
 *                 &lt;attribute name="policy" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="PER_NODE" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="eviction-percentage" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="min-eviction-check-millis" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="merge-policy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="read-backup-data" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="map-store" type="{http://www.hazelcast.com/schema/config}map-store" minOccurs="0"/>
 *         &lt;element name="near-cache" type="{http://www.hazelcast.com/schema/config}near-cache" minOccurs="0"/>
 *         &lt;element name="wan-replication-ref" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="merge-policy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="indexes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="index" type="{http://www.hazelcast.com/schema/config}index" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="entry-listeners" type="{http://www.hazelcast.com/schema/config}entry-listeners" minOccurs="0"/>
 *         &lt;element name="partition-strategy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "map", propOrder = {
    "inMemoryFormat",
    "statisticsEnabled",
    "optimizeQueries",
    "backupCount",
    "asyncBackupCount",
    "timeToLiveSeconds",
    "maxIdleSeconds",
    "evictionPolicy",
    "maxSize",
    "evictionPercentage",
    "minEvictionCheckMillis",
    "mergePolicy",
    "readBackupData",
    "mapStore",
    "nearCache",
    "wanReplicationRef",
    "indexes",
    "entryListeners",
    "partitionStrategy"
})
public class Map {

    @XmlElement(name = "in-memory-format", defaultValue = "BINARY")
    @XmlSchemaType(name = "string")
    protected InMemoryFormat inMemoryFormat;
    @XmlElement(name = "statistics-enabled", defaultValue = "true")
    protected Boolean statisticsEnabled;
    @XmlElement(name = "optimize-queries", defaultValue = "false")
    protected Boolean optimizeQueries;
    @XmlElement(name = "backup-count", defaultValue = "1")
    protected Byte backupCount;
    @XmlElement(name = "async-backup-count", defaultValue = "0")
    protected Byte asyncBackupCount;
    @XmlElement(name = "time-to-live-seconds", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected Long timeToLiveSeconds;
    @XmlElement(name = "max-idle-seconds", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected Long maxIdleSeconds;
    @XmlElement(name = "eviction-policy")
    @XmlSchemaType(name = "string")
    protected EvictionPolicy evictionPolicy;
    @XmlElement(name = "max-size", defaultValue = "0")
    protected Map.MaxSize maxSize;
    @XmlElement(name = "eviction-percentage")
    protected Byte evictionPercentage;
    @XmlElement(name = "min-eviction-check-millis", defaultValue = "100")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger minEvictionCheckMillis;
    @XmlElement(name = "merge-policy")
    protected String mergePolicy;
    @XmlElement(name = "read-backup-data", defaultValue = "false")
    protected Boolean readBackupData;
    @XmlElement(name = "map-store")
    protected MapStore mapStore;
    @XmlElement(name = "near-cache")
    protected NearCache nearCache;
    @XmlElement(name = "wan-replication-ref")
    protected Map.WanReplicationRef wanReplicationRef;
    protected Map.Indexes indexes;
    @XmlElement(name = "entry-listeners")
    protected EntryListeners entryListeners;
    @XmlElement(name = "partition-strategy")
    protected String partitionStrategy;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the inMemoryFormat property.
     * 
     * @return
     *     possible object is
     *     {@link InMemoryFormat }
     *     
     */
    public InMemoryFormat getInMemoryFormat() {
        return inMemoryFormat;
    }

    /**
     * Sets the value of the inMemoryFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link InMemoryFormat }
     *     
     */
    public void setInMemoryFormat(InMemoryFormat value) {
        this.inMemoryFormat = value;
    }

    /**
     * Gets the value of the statisticsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStatisticsEnabled() {
        return statisticsEnabled;
    }

    /**
     * Sets the value of the statisticsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStatisticsEnabled(Boolean value) {
        this.statisticsEnabled = value;
    }

    /**
     * Gets the value of the optimizeQueries property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOptimizeQueries() {
        return optimizeQueries;
    }

    /**
     * Sets the value of the optimizeQueries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOptimizeQueries(Boolean value) {
        this.optimizeQueries = value;
    }

    /**
     * Gets the value of the backupCount property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getBackupCount() {
        return backupCount;
    }

    /**
     * Sets the value of the backupCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setBackupCount(Byte value) {
        this.backupCount = value;
    }

    /**
     * Gets the value of the asyncBackupCount property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getAsyncBackupCount() {
        return asyncBackupCount;
    }

    /**
     * Sets the value of the asyncBackupCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setAsyncBackupCount(Byte value) {
        this.asyncBackupCount = value;
    }

    /**
     * Gets the value of the timeToLiveSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTimeToLiveSeconds() {
        return timeToLiveSeconds;
    }

    /**
     * Sets the value of the timeToLiveSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTimeToLiveSeconds(Long value) {
        this.timeToLiveSeconds = value;
    }

    /**
     * Gets the value of the maxIdleSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxIdleSeconds() {
        return maxIdleSeconds;
    }

    /**
     * Sets the value of the maxIdleSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxIdleSeconds(Long value) {
        this.maxIdleSeconds = value;
    }

    /**
     * Gets the value of the evictionPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link EvictionPolicy }
     *     
     */
    public EvictionPolicy getEvictionPolicy() {
        return evictionPolicy;
    }

    /**
     * Sets the value of the evictionPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link EvictionPolicy }
     *     
     */
    public void setEvictionPolicy(EvictionPolicy value) {
        this.evictionPolicy = value;
    }

    /**
     * Gets the value of the maxSize property.
     * 
     * @return
     *     possible object is
     *     {@link Map.MaxSize }
     *     
     */
    public Map.MaxSize getMaxSize() {
        return maxSize;
    }

    /**
     * Sets the value of the maxSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Map.MaxSize }
     *     
     */
    public void setMaxSize(Map.MaxSize value) {
        this.maxSize = value;
    }

    /**
     * Gets the value of the evictionPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getEvictionPercentage() {
        return evictionPercentage;
    }

    /**
     * Sets the value of the evictionPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setEvictionPercentage(Byte value) {
        this.evictionPercentage = value;
    }

    /**
     * Gets the value of the minEvictionCheckMillis property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinEvictionCheckMillis() {
        return minEvictionCheckMillis;
    }

    /**
     * Sets the value of the minEvictionCheckMillis property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinEvictionCheckMillis(BigInteger value) {
        this.minEvictionCheckMillis = value;
    }

    /**
     * Gets the value of the mergePolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMergePolicy() {
        return mergePolicy;
    }

    /**
     * Sets the value of the mergePolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMergePolicy(String value) {
        this.mergePolicy = value;
    }

    /**
     * Gets the value of the readBackupData property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReadBackupData() {
        return readBackupData;
    }

    /**
     * Sets the value of the readBackupData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReadBackupData(Boolean value) {
        this.readBackupData = value;
    }

    /**
     * Gets the value of the mapStore property.
     * 
     * @return
     *     possible object is
     *     {@link MapStore }
     *     
     */
    public MapStore getMapStore() {
        return mapStore;
    }

    /**
     * Sets the value of the mapStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapStore }
     *     
     */
    public void setMapStore(MapStore value) {
        this.mapStore = value;
    }

    /**
     * Gets the value of the nearCache property.
     * 
     * @return
     *     possible object is
     *     {@link NearCache }
     *     
     */
    public NearCache getNearCache() {
        return nearCache;
    }

    /**
     * Sets the value of the nearCache property.
     * 
     * @param value
     *     allowed object is
     *     {@link NearCache }
     *     
     */
    public void setNearCache(NearCache value) {
        this.nearCache = value;
    }

    /**
     * Gets the value of the wanReplicationRef property.
     * 
     * @return
     *     possible object is
     *     {@link Map.WanReplicationRef }
     *     
     */
    public Map.WanReplicationRef getWanReplicationRef() {
        return wanReplicationRef;
    }

    /**
     * Sets the value of the wanReplicationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Map.WanReplicationRef }
     *     
     */
    public void setWanReplicationRef(Map.WanReplicationRef value) {
        this.wanReplicationRef = value;
    }

    /**
     * Gets the value of the indexes property.
     * 
     * @return
     *     possible object is
     *     {@link Map.Indexes }
     *     
     */
    public Map.Indexes getIndexes() {
        return indexes;
    }

    /**
     * Sets the value of the indexes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Map.Indexes }
     *     
     */
    public void setIndexes(Map.Indexes value) {
        this.indexes = value;
    }

    /**
     * Gets the value of the entryListeners property.
     * 
     * @return
     *     possible object is
     *     {@link EntryListeners }
     *     
     */
    public EntryListeners getEntryListeners() {
        return entryListeners;
    }

    /**
     * Sets the value of the entryListeners property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntryListeners }
     *     
     */
    public void setEntryListeners(EntryListeners value) {
        this.entryListeners = value;
    }

    /**
     * Gets the value of the partitionStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartitionStrategy() {
        return partitionStrategy;
    }

    /**
     * Sets the value of the partitionStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartitionStrategy(String value) {
        this.partitionStrategy = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="index" type="{http://www.hazelcast.com/schema/config}index" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "index"
    })
    public static class Indexes {

        protected List<Index> index;

        /**
         * Gets the value of the index property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the index property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIndex().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Index }
         * 
         * 
         */
        public List<Index> getIndex() {
            if (index == null) {
                index = new ArrayList<Index>();
            }
            return this.index;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
     *       &lt;attribute name="policy" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="PER_NODE" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class MaxSize {

        @XmlValue
        protected BigInteger value;
        @XmlAttribute(name = "policy")
        @XmlSchemaType(name = "anySimpleType")
        protected String policy;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setValue(BigInteger value) {
            this.value = value;
        }

        /**
         * Gets the value of the policy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPolicy() {
            if (policy == null) {
                return "PER_NODE";
            } else {
                return policy;
            }
        }

        /**
         * Sets the value of the policy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPolicy(String value) {
            this.policy = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="merge-policy" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mergePolicy"
    })
    public static class WanReplicationRef {

        @XmlElement(name = "merge-policy", required = true)
        protected String mergePolicy;
        @XmlAttribute(name = "name", required = true)
        protected String name;

        /**
         * Gets the value of the mergePolicy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMergePolicy() {
            return mergePolicy;
        }

        /**
         * Sets the value of the mergePolicy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMergePolicy(String value) {
            this.mergePolicy = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
