//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for map-store complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="map-store">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="class-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="factory-class-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *         &lt;element name="write-delay-seconds" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="write-batch-size" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="write-coalescing" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="properties" type="{http://www.hazelcast.com/schema/config}properties" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="initial-mode">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.hazelcast.com/schema/config}non-space-string">
 *             &lt;enumeration value="LAZY"/>
 *             &lt;enumeration value="EAGER"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "map-store", propOrder = {
    "className",
    "factoryClassName",
    "writeDelaySeconds",
    "writeBatchSize",
    "writeCoalescing",
    "properties"
})
public class MapStore {

    @XmlElement(name = "class-name")
    protected String className;
    @XmlElement(name = "factory-class-name")
    protected String factoryClassName;
    @XmlElement(name = "write-delay-seconds", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected Long writeDelaySeconds;
    @XmlElement(name = "write-batch-size", defaultValue = "1")
    @XmlSchemaType(name = "unsignedInt")
    protected Long writeBatchSize;
    @XmlElement(name = "write-coalescing", defaultValue = "true")
    protected Boolean writeCoalescing;
    protected Properties properties;
    @XmlAttribute(name = "enabled")
    protected Boolean enabled;
    @XmlAttribute(name = "initial-mode")
    protected String initialMode;

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the factoryClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFactoryClassName() {
        return factoryClassName;
    }

    /**
     * Sets the value of the factoryClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFactoryClassName(String value) {
        this.factoryClassName = value;
    }

    /**
     * Gets the value of the writeDelaySeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getWriteDelaySeconds() {
        return writeDelaySeconds;
    }

    /**
     * Sets the value of the writeDelaySeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setWriteDelaySeconds(Long value) {
        this.writeDelaySeconds = value;
    }

    /**
     * Gets the value of the writeBatchSize property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getWriteBatchSize() {
        return writeBatchSize;
    }

    /**
     * Sets the value of the writeBatchSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setWriteBatchSize(Long value) {
        this.writeBatchSize = value;
    }

    /**
     * Gets the value of the writeCoalescing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWriteCoalescing() {
        return writeCoalescing;
    }

    /**
     * Sets the value of the writeCoalescing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWriteCoalescing(Boolean value) {
        this.writeCoalescing = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link Properties }
     *     
     */
    public Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Properties }
     *     
     */
    public void setProperties(Properties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEnabled() {
        if (enabled == null) {
            return true;
        } else {
            return enabled;
        }
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnabled(Boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the initialMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialMode() {
        return initialMode;
    }

    /**
     * Sets the value of the initialMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialMode(String value) {
        this.initialMode = value;
    }

}
