//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for memory-unit.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="memory-unit">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BYTES"/>
 *     &lt;enumeration value="KILOBYTES"/>
 *     &lt;enumeration value="MEGABYTES"/>
 *     &lt;enumeration value="GIGABYTES"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "memory-unit")
@XmlEnum
public enum MemoryUnit {

    BYTES,
    KILOBYTES,
    MEGABYTES,
    GIGABYTES;

    public String value() {
        return name();
    }

    public static MemoryUnit fromValue(String v) {
        return valueOf(v);
    }

}
