//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for multicast complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="multicast">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="multicast-group" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="multicast-port" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *         &lt;element name="multicast-timeout-seconds" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="multicast-time-to-live" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="trusted-interfaces" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="interface" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "multicast", propOrder = {
    "multicastGroup",
    "multicastPort",
    "multicastTimeoutSeconds",
    "multicastTimeToLive",
    "trustedInterfaces"
})
public class Multicast {

    @XmlElement(name = "multicast-group", defaultValue = "224.2.2.3")
    protected String multicastGroup;
    @XmlElement(name = "multicast-port", defaultValue = "54327")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer multicastPort;
    @XmlElement(name = "multicast-timeout-seconds", defaultValue = "2")
    protected Integer multicastTimeoutSeconds;
    @XmlElement(name = "multicast-time-to-live", defaultValue = "32")
    protected Integer multicastTimeToLive;
    @XmlElement(name = "trusted-interfaces")
    protected Multicast.TrustedInterfaces trustedInterfaces;
    @XmlAttribute(name = "enabled")
    protected Boolean enabled;

    /**
     * Gets the value of the multicastGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMulticastGroup() {
        return multicastGroup;
    }

    /**
     * Sets the value of the multicastGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMulticastGroup(String value) {
        this.multicastGroup = value;
    }

    /**
     * Gets the value of the multicastPort property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMulticastPort() {
        return multicastPort;
    }

    /**
     * Sets the value of the multicastPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMulticastPort(Integer value) {
        this.multicastPort = value;
    }

    /**
     * Gets the value of the multicastTimeoutSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMulticastTimeoutSeconds() {
        return multicastTimeoutSeconds;
    }

    /**
     * Sets the value of the multicastTimeoutSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMulticastTimeoutSeconds(Integer value) {
        this.multicastTimeoutSeconds = value;
    }

    /**
     * Gets the value of the multicastTimeToLive property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMulticastTimeToLive() {
        return multicastTimeToLive;
    }

    /**
     * Sets the value of the multicastTimeToLive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMulticastTimeToLive(Integer value) {
        this.multicastTimeToLive = value;
    }

    /**
     * Gets the value of the trustedInterfaces property.
     * 
     * @return
     *     possible object is
     *     {@link Multicast.TrustedInterfaces }
     *     
     */
    public Multicast.TrustedInterfaces getTrustedInterfaces() {
        return trustedInterfaces;
    }

    /**
     * Sets the value of the trustedInterfaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Multicast.TrustedInterfaces }
     *     
     */
    public void setTrustedInterfaces(Multicast.TrustedInterfaces value) {
        this.trustedInterfaces = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEnabled() {
        if (enabled == null) {
            return true;
        } else {
            return enabled;
        }
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnabled(Boolean value) {
        this.enabled = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="interface" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_interface"
    })
    public static class TrustedInterfaces {

        @XmlElement(name = "interface")
        protected List<String> _interface;

        /**
         * Gets the value of the interface property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the interface property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInterface().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getInterface() {
            if (_interface == null) {
                _interface = new ArrayList<String>();
            }
            return this._interface;
        }

    }

}
