//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for native-memory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="native-memory">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="size" type="{http://www.hazelcast.com/schema/config}memory-size" minOccurs="0"/>
 *         &lt;element name="min-block-size" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="page-size" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="metadata-space-percentage" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="3"/>
 *               &lt;fractionDigits value="1"/>
 *               &lt;minInclusive value="5"/>
 *               &lt;maxInclusive value="95"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="allocator-type" type="{http://www.hazelcast.com/schema/config}memory-allocator-type" default="POOLED" />
 *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "native-memory", propOrder = {
    "size",
    "minBlockSize",
    "pageSize",
    "metadataSpacePercentage"
})
public class NativeMemory {

    protected MemorySize size;
    @XmlElement(name = "min-block-size")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger minBlockSize;
    @XmlElement(name = "page-size")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger pageSize;
    @XmlElement(name = "metadata-space-percentage")
    protected BigDecimal metadataSpacePercentage;
    @XmlAttribute(name = "allocator-type")
    protected MemoryAllocatorType allocatorType;
    @XmlAttribute(name = "enabled")
    protected Boolean enabled;

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link MemorySize }
     *     
     */
    public MemorySize getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemorySize }
     *     
     */
    public void setSize(MemorySize value) {
        this.size = value;
    }

    /**
     * Gets the value of the minBlockSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinBlockSize() {
        return minBlockSize;
    }

    /**
     * Sets the value of the minBlockSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinBlockSize(BigInteger value) {
        this.minBlockSize = value;
    }

    /**
     * Gets the value of the pageSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPageSize() {
        return pageSize;
    }

    /**
     * Sets the value of the pageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPageSize(BigInteger value) {
        this.pageSize = value;
    }

    /**
     * Gets the value of the metadataSpacePercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMetadataSpacePercentage() {
        return metadataSpacePercentage;
    }

    /**
     * Sets the value of the metadataSpacePercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMetadataSpacePercentage(BigDecimal value) {
        this.metadataSpacePercentage = value;
    }

    /**
     * Gets the value of the allocatorType property.
     * 
     * @return
     *     possible object is
     *     {@link MemoryAllocatorType }
     *     
     */
    public MemoryAllocatorType getAllocatorType() {
        if (allocatorType == null) {
            return MemoryAllocatorType.POOLED;
        } else {
            return allocatorType;
        }
    }

    /**
     * Sets the value of the allocatorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemoryAllocatorType }
     *     
     */
    public void setAllocatorType(MemoryAllocatorType value) {
        this.allocatorType = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEnabled() {
        if (enabled == null) {
            return false;
        } else {
            return enabled;
        }
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnabled(Boolean value) {
        this.enabled = value;
    }

}
