//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for near-cache complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="near-cache">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="max-size" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="time-to-live-seconds" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="max-idle-seconds" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="eviction-policy" type="{http://www.hazelcast.com/schema/config}eviction-policy" minOccurs="0"/>
 *         &lt;element name="invalidate-on-change" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="in-memory-format" type="{http://www.hazelcast.com/schema/config}in-memory-format" minOccurs="0"/>
 *         &lt;element name="cache-local-entries" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "near-cache", propOrder = {
    "maxSize",
    "timeToLiveSeconds",
    "maxIdleSeconds",
    "evictionPolicy",
    "invalidateOnChange",
    "inMemoryFormat",
    "cacheLocalEntries"
})
public class NearCache {

    @XmlElement(name = "max-size", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected Long maxSize;
    @XmlElement(name = "time-to-live-seconds", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected Long timeToLiveSeconds;
    @XmlElement(name = "max-idle-seconds", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected Long maxIdleSeconds;
    @XmlElement(name = "eviction-policy", defaultValue = "LRU")
    @XmlSchemaType(name = "string")
    protected EvictionPolicy evictionPolicy;
    @XmlElement(name = "invalidate-on-change", defaultValue = "true")
    protected Boolean invalidateOnChange;
    @XmlElement(name = "in-memory-format", defaultValue = "BINARY")
    @XmlSchemaType(name = "string")
    protected InMemoryFormat inMemoryFormat;
    @XmlElement(name = "cache-local-entries", defaultValue = "false")
    protected Boolean cacheLocalEntries;

    /**
     * Gets the value of the maxSize property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxSize() {
        return maxSize;
    }

    /**
     * Sets the value of the maxSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxSize(Long value) {
        this.maxSize = value;
    }

    /**
     * Gets the value of the timeToLiveSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTimeToLiveSeconds() {
        return timeToLiveSeconds;
    }

    /**
     * Sets the value of the timeToLiveSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTimeToLiveSeconds(Long value) {
        this.timeToLiveSeconds = value;
    }

    /**
     * Gets the value of the maxIdleSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxIdleSeconds() {
        return maxIdleSeconds;
    }

    /**
     * Sets the value of the maxIdleSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxIdleSeconds(Long value) {
        this.maxIdleSeconds = value;
    }

    /**
     * Gets the value of the evictionPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link EvictionPolicy }
     *     
     */
    public EvictionPolicy getEvictionPolicy() {
        return evictionPolicy;
    }

    /**
     * Sets the value of the evictionPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link EvictionPolicy }
     *     
     */
    public void setEvictionPolicy(EvictionPolicy value) {
        this.evictionPolicy = value;
    }

    /**
     * Gets the value of the invalidateOnChange property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInvalidateOnChange() {
        return invalidateOnChange;
    }

    /**
     * Sets the value of the invalidateOnChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInvalidateOnChange(Boolean value) {
        this.invalidateOnChange = value;
    }

    /**
     * Gets the value of the inMemoryFormat property.
     * 
     * @return
     *     possible object is
     *     {@link InMemoryFormat }
     *     
     */
    public InMemoryFormat getInMemoryFormat() {
        return inMemoryFormat;
    }

    /**
     * Sets the value of the inMemoryFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link InMemoryFormat }
     *     
     */
    public void setInMemoryFormat(InMemoryFormat value) {
        this.inMemoryFormat = value;
    }

    /**
     * Gets the value of the cacheLocalEntries property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCacheLocalEntries() {
        return cacheLocalEntries;
    }

    /**
     * Sets the value of the cacheLocalEntries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCacheLocalEntries(Boolean value) {
        this.cacheLocalEntries = value;
    }

}
