//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for network complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="network">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="public-address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="port" type="{http://www.hazelcast.com/schema/config}port" minOccurs="0"/>
 *         &lt;element name="reuse-address" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="outbound-ports" type="{http://www.hazelcast.com/schema/config}outbound-ports" minOccurs="0"/>
 *         &lt;element name="join" type="{http://www.hazelcast.com/schema/config}join" minOccurs="0"/>
 *         &lt;element name="interfaces" type="{http://www.hazelcast.com/schema/config}interfaces" minOccurs="0"/>
 *         &lt;element name="ssl" type="{http://www.hazelcast.com/schema/config}ssl" minOccurs="0"/>
 *         &lt;element name="socket-interceptor" type="{http://www.hazelcast.com/schema/config}socket-interceptor" minOccurs="0"/>
 *         &lt;element name="symmetric-encryption" type="{http://www.hazelcast.com/schema/config}symmetric-encryption" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "network", propOrder = {
    "publicAddress",
    "port",
    "reuseAddress",
    "outboundPorts",
    "join",
    "interfaces",
    "ssl",
    "socketInterceptor",
    "symmetricEncryption"
})
public class Network {

    @XmlElement(name = "public-address")
    protected String publicAddress;
    protected Port port;
    @XmlElement(name = "reuse-address", defaultValue = "false")
    protected Boolean reuseAddress;
    @XmlElement(name = "outbound-ports")
    protected OutboundPorts outboundPorts;
    protected Join join;
    protected Interfaces interfaces;
    protected Ssl ssl;
    @XmlElement(name = "socket-interceptor")
    protected SocketInterceptor socketInterceptor;
    @XmlElement(name = "symmetric-encryption")
    protected SymmetricEncryption symmetricEncryption;

    /**
     * Gets the value of the publicAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicAddress() {
        return publicAddress;
    }

    /**
     * Sets the value of the publicAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicAddress(String value) {
        this.publicAddress = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link Port }
     *     
     */
    public Port getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link Port }
     *     
     */
    public void setPort(Port value) {
        this.port = value;
    }

    /**
     * Gets the value of the reuseAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReuseAddress() {
        return reuseAddress;
    }

    /**
     * Sets the value of the reuseAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReuseAddress(Boolean value) {
        this.reuseAddress = value;
    }

    /**
     * Gets the value of the outboundPorts property.
     * 
     * @return
     *     possible object is
     *     {@link OutboundPorts }
     *     
     */
    public OutboundPorts getOutboundPorts() {
        return outboundPorts;
    }

    /**
     * Sets the value of the outboundPorts property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutboundPorts }
     *     
     */
    public void setOutboundPorts(OutboundPorts value) {
        this.outboundPorts = value;
    }

    /**
     * Gets the value of the join property.
     * 
     * @return
     *     possible object is
     *     {@link Join }
     *     
     */
    public Join getJoin() {
        return join;
    }

    /**
     * Sets the value of the join property.
     * 
     * @param value
     *     allowed object is
     *     {@link Join }
     *     
     */
    public void setJoin(Join value) {
        this.join = value;
    }

    /**
     * Gets the value of the interfaces property.
     * 
     * @return
     *     possible object is
     *     {@link Interfaces }
     *     
     */
    public Interfaces getInterfaces() {
        return interfaces;
    }

    /**
     * Sets the value of the interfaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interfaces }
     *     
     */
    public void setInterfaces(Interfaces value) {
        this.interfaces = value;
    }

    /**
     * Gets the value of the ssl property.
     * 
     * @return
     *     possible object is
     *     {@link Ssl }
     *     
     */
    public Ssl getSsl() {
        return ssl;
    }

    /**
     * Sets the value of the ssl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ssl }
     *     
     */
    public void setSsl(Ssl value) {
        this.ssl = value;
    }

    /**
     * Gets the value of the socketInterceptor property.
     * 
     * @return
     *     possible object is
     *     {@link SocketInterceptor }
     *     
     */
    public SocketInterceptor getSocketInterceptor() {
        return socketInterceptor;
    }

    /**
     * Sets the value of the socketInterceptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link SocketInterceptor }
     *     
     */
    public void setSocketInterceptor(SocketInterceptor value) {
        this.socketInterceptor = value;
    }

    /**
     * Gets the value of the symmetricEncryption property.
     * 
     * @return
     *     possible object is
     *     {@link SymmetricEncryption }
     *     
     */
    public SymmetricEncryption getSymmetricEncryption() {
        return symmetricEncryption;
    }

    /**
     * Sets the value of the symmetricEncryption property.
     * 
     * @param value
     *     allowed object is
     *     {@link SymmetricEncryption }
     *     
     */
    public void setSymmetricEncryption(SymmetricEncryption value) {
        this.symmetricEncryption = value;
    }

}
