//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hazelcast.schema.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hazelcast.schema.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Multicast }
     * 
     */
    public Multicast createMulticast() {
        return new Multicast();
    }

    /**
     * Create an instance of {@link BasePermission }
     * 
     */
    public BasePermission createBasePermission() {
        return new BasePermission();
    }

    /**
     * Create an instance of {@link CacheEntryListener }
     * 
     */
    public CacheEntryListener createCacheEntryListener() {
        return new CacheEntryListener();
    }

    /**
     * Create an instance of {@link Serialization }
     * 
     */
    public Serialization createSerialization() {
        return new Serialization();
    }

    /**
     * Create an instance of {@link Topic }
     * 
     */
    public Topic createTopic() {
        return new Topic();
    }

    /**
     * Create an instance of {@link Set }
     * 
     */
    public Set createSet() {
        return new Set();
    }

    /**
     * Create an instance of {@link List }
     * 
     */
    public List createList() {
        return new List();
    }

    /**
     * Create an instance of {@link Cache }
     * 
     */
    public Cache createCache() {
        return new Cache();
    }

    /**
     * Create an instance of {@link Map }
     * 
     */
    public Map createMap() {
        return new Map();
    }

    /**
     * Create an instance of {@link Queue }
     * 
     */
    public Queue createQueue() {
        return new Queue();
    }

    /**
     * Create an instance of {@link PartitionGroup }
     * 
     */
    public PartitionGroup createPartitionGroup() {
        return new PartitionGroup();
    }

    /**
     * Create an instance of {@link QueueStore }
     * 
     */
    public QueueStore createQueueStore() {
        return new QueueStore();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Import }
     * 
     */
    public Import createImport() {
        return new Import();
    }

    /**
     * Create an instance of {@link Hazelcast }
     * 
     */
    public Hazelcast createHazelcast() {
        return new Hazelcast();
    }

    /**
     * Create an instance of {@link ClusterGroup }
     * 
     */
    public ClusterGroup createClusterGroup() {
        return new ClusterGroup();
    }

    /**
     * Create an instance of {@link ManagementCenter }
     * 
     */
    public ManagementCenter createManagementCenter() {
        return new ManagementCenter();
    }

    /**
     * Create an instance of {@link WanReplication }
     * 
     */
    public WanReplication createWanReplication() {
        return new WanReplication();
    }

    /**
     * Create an instance of {@link Network }
     * 
     */
    public Network createNetwork() {
        return new Network();
    }

    /**
     * Create an instance of {@link ExecutorService }
     * 
     */
    public ExecutorService createExecutorService() {
        return new ExecutorService();
    }

    /**
     * Create an instance of {@link Multimap }
     * 
     */
    public Multimap createMultimap() {
        return new Multimap();
    }

    /**
     * Create an instance of {@link Replicatedmap }
     * 
     */
    public Replicatedmap createReplicatedmap() {
        return new Replicatedmap();
    }

    /**
     * Create an instance of {@link Jobtracker }
     * 
     */
    public Jobtracker createJobtracker() {
        return new Jobtracker();
    }

    /**
     * Create an instance of {@link Semaphore }
     * 
     */
    public Semaphore createSemaphore() {
        return new Semaphore();
    }

    /**
     * Create an instance of {@link Listeners }
     * 
     */
    public Listeners createListeners() {
        return new Listeners();
    }

    /**
     * Create an instance of {@link NativeMemory }
     * 
     */
    public NativeMemory createNativeMemory() {
        return new NativeMemory();
    }

    /**
     * Create an instance of {@link Services }
     * 
     */
    public Services createServices() {
        return new Services();
    }

    /**
     * Create an instance of {@link Security }
     * 
     */
    public Security createSecurity() {
        return new Security();
    }

    /**
     * Create an instance of {@link MemberAttributes }
     * 
     */
    public MemberAttributes createMemberAttributes() {
        return new MemberAttributes();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link InstancePermission }
     * 
     */
    public InstancePermission createInstancePermission() {
        return new InstancePermission();
    }

    /**
     * Create an instance of {@link TcpIp }
     * 
     */
    public TcpIp createTcpIp() {
        return new TcpIp();
    }

    /**
     * Create an instance of {@link Ssl }
     * 
     */
    public Ssl createSsl() {
        return new Ssl();
    }

    /**
     * Create an instance of {@link EntryListeners }
     * 
     */
    public EntryListeners createEntryListeners() {
        return new EntryListeners();
    }

    /**
     * Create an instance of {@link Permissions }
     * 
     */
    public Permissions createPermissions() {
        return new Permissions();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Join }
     * 
     */
    public Join createJoin() {
        return new Join();
    }

    /**
     * Create an instance of {@link SocketInterceptor }
     * 
     */
    public SocketInterceptor createSocketInterceptor() {
        return new SocketInterceptor();
    }

    /**
     * Create an instance of {@link MemorySize }
     * 
     */
    public MemorySize createMemorySize() {
        return new MemorySize();
    }

    /**
     * Create an instance of {@link Interceptors }
     * 
     */
    public Interceptors createInterceptors() {
        return new Interceptors();
    }

    /**
     * Create an instance of {@link SecurityObject }
     * 
     */
    public SecurityObject createSecurityObject() {
        return new SecurityObject();
    }

    /**
     * Create an instance of {@link SerializationFactory }
     * 
     */
    public SerializationFactory createSerializationFactory() {
        return new SerializationFactory();
    }

    /**
     * Create an instance of {@link ListenerBase }
     * 
     */
    public ListenerBase createListenerBase() {
        return new ListenerBase();
    }

    /**
     * Create an instance of {@link CacheEntryListeners }
     * 
     */
    public CacheEntryListeners createCacheEntryListeners() {
        return new CacheEntryListeners();
    }

    /**
     * Create an instance of {@link Index }
     * 
     */
    public Index createIndex() {
        return new Index();
    }

    /**
     * Create an instance of {@link EndPoints }
     * 
     */
    public EndPoints createEndPoints() {
        return new EndPoints();
    }

    /**
     * Create an instance of {@link ItemListener }
     * 
     */
    public ItemListener createItemListener() {
        return new ItemListener();
    }

    /**
     * Create an instance of {@link EntryListener }
     * 
     */
    public EntryListener createEntryListener() {
        return new EntryListener();
    }

    /**
     * Create an instance of {@link MapStore }
     * 
     */
    public MapStore createMapStore() {
        return new MapStore();
    }

    /**
     * Create an instance of {@link Port }
     * 
     */
    public Port createPort() {
        return new Port();
    }

    /**
     * Create an instance of {@link LoginModules }
     * 
     */
    public LoginModules createLoginModules() {
        return new LoginModules();
    }

    /**
     * Create an instance of {@link SymmetricEncryption }
     * 
     */
    public SymmetricEncryption createSymmetricEncryption() {
        return new SymmetricEncryption();
    }

    /**
     * Create an instance of {@link Actions }
     * 
     */
    public Actions createActions() {
        return new Actions();
    }

    /**
     * Create an instance of {@link Serializer }
     * 
     */
    public Serializer createSerializer() {
        return new Serializer();
    }

    /**
     * Create an instance of {@link Interceptor }
     * 
     */
    public Interceptor createInterceptor() {
        return new Interceptor();
    }

    /**
     * Create an instance of {@link NearCache }
     * 
     */
    public NearCache createNearCache() {
        return new NearCache();
    }

    /**
     * Create an instance of {@link CacheEviction }
     * 
     */
    public CacheEviction createCacheEviction() {
        return new CacheEviction();
    }

    /**
     * Create an instance of {@link Interfaces }
     * 
     */
    public Interfaces createInterfaces() {
        return new Interfaces();
    }

    /**
     * Create an instance of {@link TargetCluster }
     * 
     */
    public TargetCluster createTargetCluster() {
        return new TargetCluster();
    }

    /**
     * Create an instance of {@link LoginModule }
     * 
     */
    public LoginModule createLoginModule() {
        return new LoginModule();
    }

    /**
     * Create an instance of {@link OutboundPorts }
     * 
     */
    public OutboundPorts createOutboundPorts() {
        return new OutboundPorts();
    }

    /**
     * Create an instance of {@link Attributes }
     * 
     */
    public Attributes createAttributes() {
        return new Attributes();
    }

    /**
     * Create an instance of {@link Aws }
     * 
     */
    public Aws createAws() {
        return new Aws();
    }

    /**
     * Create an instance of {@link Service.Configuration }
     * 
     */
    public Service.Configuration createServiceConfiguration() {
        return new Service.Configuration();
    }

    /**
     * Create an instance of {@link Multicast.TrustedInterfaces }
     * 
     */
    public Multicast.TrustedInterfaces createMulticastTrustedInterfaces() {
        return new Multicast.TrustedInterfaces();
    }

    /**
     * Create an instance of {@link BasePermission.Endpoints }
     * 
     */
    public BasePermission.Endpoints createBasePermissionEndpoints() {
        return new BasePermission.Endpoints();
    }

    /**
     * Create an instance of {@link CacheEntryListener.CacheEntryListenerFactory }
     * 
     */
    public CacheEntryListener.CacheEntryListenerFactory createCacheEntryListenerCacheEntryListenerFactory() {
        return new CacheEntryListener.CacheEntryListenerFactory();
    }

    /**
     * Create an instance of {@link CacheEntryListener.CacheEntryEventFilterFactory }
     * 
     */
    public CacheEntryListener.CacheEntryEventFilterFactory createCacheEntryListenerCacheEntryEventFilterFactory() {
        return new CacheEntryListener.CacheEntryEventFilterFactory();
    }

    /**
     * Create an instance of {@link Serialization.DataSerializableFactories }
     * 
     */
    public Serialization.DataSerializableFactories createSerializationDataSerializableFactories() {
        return new Serialization.DataSerializableFactories();
    }

    /**
     * Create an instance of {@link Serialization.PortableFactories }
     * 
     */
    public Serialization.PortableFactories createSerializationPortableFactories() {
        return new Serialization.PortableFactories();
    }

    /**
     * Create an instance of {@link Serialization.Serializers }
     * 
     */
    public Serialization.Serializers createSerializationSerializers() {
        return new Serialization.Serializers();
    }

    /**
     * Create an instance of {@link Topic.MessageListeners }
     * 
     */
    public Topic.MessageListeners createTopicMessageListeners() {
        return new Topic.MessageListeners();
    }

    /**
     * Create an instance of {@link Set.ItemListeners }
     * 
     */
    public Set.ItemListeners createSetItemListeners() {
        return new Set.ItemListeners();
    }

    /**
     * Create an instance of {@link List.ItemListeners }
     * 
     */
    public List.ItemListeners createListItemListeners() {
        return new List.ItemListeners();
    }

    /**
     * Create an instance of {@link Cache.KeyType }
     * 
     */
    public Cache.KeyType createCacheKeyType() {
        return new Cache.KeyType();
    }

    /**
     * Create an instance of {@link Cache.ValueType }
     * 
     */
    public Cache.ValueType createCacheValueType() {
        return new Cache.ValueType();
    }

    /**
     * Create an instance of {@link Cache.CacheLoaderFactory }
     * 
     */
    public Cache.CacheLoaderFactory createCacheCacheLoaderFactory() {
        return new Cache.CacheLoaderFactory();
    }

    /**
     * Create an instance of {@link Cache.CacheWriterFactory }
     * 
     */
    public Cache.CacheWriterFactory createCacheCacheWriterFactory() {
        return new Cache.CacheWriterFactory();
    }

    /**
     * Create an instance of {@link Cache.ExpiryPolicyFactory }
     * 
     */
    public Cache.ExpiryPolicyFactory createCacheExpiryPolicyFactory() {
        return new Cache.ExpiryPolicyFactory();
    }

    /**
     * Create an instance of {@link Map.MaxSize }
     * 
     */
    public Map.MaxSize createMapMaxSize() {
        return new Map.MaxSize();
    }

    /**
     * Create an instance of {@link Map.WanReplicationRef }
     * 
     */
    public Map.WanReplicationRef createMapWanReplicationRef() {
        return new Map.WanReplicationRef();
    }

    /**
     * Create an instance of {@link Map.Indexes }
     * 
     */
    public Map.Indexes createMapIndexes() {
        return new Map.Indexes();
    }

    /**
     * Create an instance of {@link Queue.ItemListeners }
     * 
     */
    public Queue.ItemListeners createQueueItemListeners() {
        return new Queue.ItemListeners();
    }

    /**
     * Create an instance of {@link PartitionGroup.MemberGroup }
     * 
     */
    public PartitionGroup.MemberGroup createPartitionGroupMemberGroup() {
        return new PartitionGroup.MemberGroup();
    }

}
