//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for permissions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="permissions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="all-permissions" type="{http://www.hazelcast.com/schema/config}base-permission" minOccurs="0"/>
 *         &lt;element name="map-permission" type="{http://www.hazelcast.com/schema/config}instance-permission" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="queue-permission" type="{http://www.hazelcast.com/schema/config}instance-permission" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="multimap-permission" type="{http://www.hazelcast.com/schema/config}instance-permission" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="topic-permission" type="{http://www.hazelcast.com/schema/config}instance-permission" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="list-permission" type="{http://www.hazelcast.com/schema/config}instance-permission" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="set-permission" type="{http://www.hazelcast.com/schema/config}instance-permission" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="lock-permission" type="{http://www.hazelcast.com/schema/config}instance-permission" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="atomic-long-permission" type="{http://www.hazelcast.com/schema/config}instance-permission" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="countdown-latch-permission" type="{http://www.hazelcast.com/schema/config}instance-permission" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="semaphore-permission" type="{http://www.hazelcast.com/schema/config}instance-permission" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="id-generator-permission" type="{http://www.hazelcast.com/schema/config}instance-permission" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="executor-service-permission" type="{http://www.hazelcast.com/schema/config}instance-permission" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="transaction-permission" type="{http://www.hazelcast.com/schema/config}base-permission" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "permissions", propOrder = {
    "allPermissions",
    "mapPermission",
    "queuePermission",
    "multimapPermission",
    "topicPermission",
    "listPermission",
    "setPermission",
    "lockPermission",
    "atomicLongPermission",
    "countdownLatchPermission",
    "semaphorePermission",
    "idGeneratorPermission",
    "executorServicePermission",
    "transactionPermission"
})
public class Permissions {

    @XmlElement(name = "all-permissions")
    protected BasePermission allPermissions;
    @XmlElement(name = "map-permission")
    protected List<InstancePermission> mapPermission;
    @XmlElement(name = "queue-permission")
    protected List<InstancePermission> queuePermission;
    @XmlElement(name = "multimap-permission")
    protected List<InstancePermission> multimapPermission;
    @XmlElement(name = "topic-permission")
    protected List<InstancePermission> topicPermission;
    @XmlElement(name = "list-permission")
    protected List<InstancePermission> listPermission;
    @XmlElement(name = "set-permission")
    protected List<InstancePermission> setPermission;
    @XmlElement(name = "lock-permission")
    protected List<InstancePermission> lockPermission;
    @XmlElement(name = "atomic-long-permission")
    protected List<InstancePermission> atomicLongPermission;
    @XmlElement(name = "countdown-latch-permission")
    protected List<InstancePermission> countdownLatchPermission;
    @XmlElement(name = "semaphore-permission")
    protected List<InstancePermission> semaphorePermission;
    @XmlElement(name = "id-generator-permission")
    protected List<InstancePermission> idGeneratorPermission;
    @XmlElement(name = "executor-service-permission")
    protected List<InstancePermission> executorServicePermission;
    @XmlElement(name = "transaction-permission")
    protected BasePermission transactionPermission;

    /**
     * Gets the value of the allPermissions property.
     * 
     * @return
     *     possible object is
     *     {@link BasePermission }
     *     
     */
    public BasePermission getAllPermissions() {
        return allPermissions;
    }

    /**
     * Sets the value of the allPermissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasePermission }
     *     
     */
    public void setAllPermissions(BasePermission value) {
        this.allPermissions = value;
    }

    /**
     * Gets the value of the mapPermission property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mapPermission property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMapPermission().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstancePermission }
     * 
     * 
     */
    public List<InstancePermission> getMapPermission() {
        if (mapPermission == null) {
            mapPermission = new ArrayList<InstancePermission>();
        }
        return this.mapPermission;
    }

    /**
     * Gets the value of the queuePermission property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the queuePermission property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQueuePermission().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstancePermission }
     * 
     * 
     */
    public List<InstancePermission> getQueuePermission() {
        if (queuePermission == null) {
            queuePermission = new ArrayList<InstancePermission>();
        }
        return this.queuePermission;
    }

    /**
     * Gets the value of the multimapPermission property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the multimapPermission property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMultimapPermission().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstancePermission }
     * 
     * 
     */
    public List<InstancePermission> getMultimapPermission() {
        if (multimapPermission == null) {
            multimapPermission = new ArrayList<InstancePermission>();
        }
        return this.multimapPermission;
    }

    /**
     * Gets the value of the topicPermission property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the topicPermission property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTopicPermission().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstancePermission }
     * 
     * 
     */
    public List<InstancePermission> getTopicPermission() {
        if (topicPermission == null) {
            topicPermission = new ArrayList<InstancePermission>();
        }
        return this.topicPermission;
    }

    /**
     * Gets the value of the listPermission property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listPermission property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListPermission().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstancePermission }
     * 
     * 
     */
    public List<InstancePermission> getListPermission() {
        if (listPermission == null) {
            listPermission = new ArrayList<InstancePermission>();
        }
        return this.listPermission;
    }

    /**
     * Gets the value of the setPermission property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the setPermission property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSetPermission().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstancePermission }
     * 
     * 
     */
    public List<InstancePermission> getSetPermission() {
        if (setPermission == null) {
            setPermission = new ArrayList<InstancePermission>();
        }
        return this.setPermission;
    }

    /**
     * Gets the value of the lockPermission property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lockPermission property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLockPermission().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstancePermission }
     * 
     * 
     */
    public List<InstancePermission> getLockPermission() {
        if (lockPermission == null) {
            lockPermission = new ArrayList<InstancePermission>();
        }
        return this.lockPermission;
    }

    /**
     * Gets the value of the atomicLongPermission property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the atomicLongPermission property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAtomicLongPermission().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstancePermission }
     * 
     * 
     */
    public List<InstancePermission> getAtomicLongPermission() {
        if (atomicLongPermission == null) {
            atomicLongPermission = new ArrayList<InstancePermission>();
        }
        return this.atomicLongPermission;
    }

    /**
     * Gets the value of the countdownLatchPermission property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the countdownLatchPermission property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCountdownLatchPermission().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstancePermission }
     * 
     * 
     */
    public List<InstancePermission> getCountdownLatchPermission() {
        if (countdownLatchPermission == null) {
            countdownLatchPermission = new ArrayList<InstancePermission>();
        }
        return this.countdownLatchPermission;
    }

    /**
     * Gets the value of the semaphorePermission property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the semaphorePermission property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSemaphorePermission().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstancePermission }
     * 
     * 
     */
    public List<InstancePermission> getSemaphorePermission() {
        if (semaphorePermission == null) {
            semaphorePermission = new ArrayList<InstancePermission>();
        }
        return this.semaphorePermission;
    }

    /**
     * Gets the value of the idGeneratorPermission property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the idGeneratorPermission property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdGeneratorPermission().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstancePermission }
     * 
     * 
     */
    public List<InstancePermission> getIdGeneratorPermission() {
        if (idGeneratorPermission == null) {
            idGeneratorPermission = new ArrayList<InstancePermission>();
        }
        return this.idGeneratorPermission;
    }

    /**
     * Gets the value of the executorServicePermission property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the executorServicePermission property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExecutorServicePermission().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstancePermission }
     * 
     * 
     */
    public List<InstancePermission> getExecutorServicePermission() {
        if (executorServicePermission == null) {
            executorServicePermission = new ArrayList<InstancePermission>();
        }
        return this.executorServicePermission;
    }

    /**
     * Gets the value of the transactionPermission property.
     * 
     * @return
     *     possible object is
     *     {@link BasePermission }
     *     
     */
    public BasePermission getTransactionPermission() {
        return transactionPermission;
    }

    /**
     * Sets the value of the transactionPermission property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasePermission }
     *     
     */
    public void setTransactionPermission(BasePermission value) {
        this.transactionPermission = value;
    }

}
