//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for queue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="queue">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="statistics-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="max-size" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="backup-count" type="{http://www.hazelcast.com/schema/config}backup-count" minOccurs="0"/>
 *         &lt;element name="async-backup-count" type="{http://www.hazelcast.com/schema/config}backup-count" minOccurs="0"/>
 *         &lt;element name="empty-queue-ttl" type="{http://www.hazelcast.com/schema/config}empty-queue-ttl" minOccurs="0"/>
 *         &lt;element name="item-listeners" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="item-listener" type="{http://www.hazelcast.com/schema/config}item-listener" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.hazelcast.com/schema/config}queue-store" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" default="default">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "queue", propOrder = {
    "statisticsEnabled",
    "maxSize",
    "backupCount",
    "asyncBackupCount",
    "emptyQueueTtl",
    "itemListeners",
    "queueStore"
})
public class Queue {

    @XmlElement(name = "statistics-enabled", defaultValue = "true")
    protected Boolean statisticsEnabled;
    @XmlElement(name = "max-size", defaultValue = "0")
    @XmlSchemaType(name = "unsignedInt")
    protected Long maxSize;
    @XmlElement(name = "backup-count", defaultValue = "1")
    protected Byte backupCount;
    @XmlElement(name = "async-backup-count", defaultValue = "0")
    protected Byte asyncBackupCount;
    @XmlElement(name = "empty-queue-ttl", defaultValue = "-1")
    protected Integer emptyQueueTtl;
    @XmlElement(name = "item-listeners")
    protected Queue.ItemListeners itemListeners;
    @XmlElement(name = "queue-store")
    protected QueueStore queueStore;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the statisticsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStatisticsEnabled() {
        return statisticsEnabled;
    }

    /**
     * Sets the value of the statisticsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStatisticsEnabled(Boolean value) {
        this.statisticsEnabled = value;
    }

    /**
     * Gets the value of the maxSize property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxSize() {
        return maxSize;
    }

    /**
     * Sets the value of the maxSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxSize(Long value) {
        this.maxSize = value;
    }

    /**
     * Gets the value of the backupCount property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getBackupCount() {
        return backupCount;
    }

    /**
     * Sets the value of the backupCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setBackupCount(Byte value) {
        this.backupCount = value;
    }

    /**
     * Gets the value of the asyncBackupCount property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getAsyncBackupCount() {
        return asyncBackupCount;
    }

    /**
     * Sets the value of the asyncBackupCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setAsyncBackupCount(Byte value) {
        this.asyncBackupCount = value;
    }

    /**
     * Gets the value of the emptyQueueTtl property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEmptyQueueTtl() {
        return emptyQueueTtl;
    }

    /**
     * Sets the value of the emptyQueueTtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEmptyQueueTtl(Integer value) {
        this.emptyQueueTtl = value;
    }

    /**
     * Gets the value of the itemListeners property.
     * 
     * @return
     *     possible object is
     *     {@link Queue.ItemListeners }
     *     
     */
    public Queue.ItemListeners getItemListeners() {
        return itemListeners;
    }

    /**
     * Sets the value of the itemListeners property.
     * 
     * @param value
     *     allowed object is
     *     {@link Queue.ItemListeners }
     *     
     */
    public void setItemListeners(Queue.ItemListeners value) {
        this.itemListeners = value;
    }

    /**
     * Gets the value of the queueStore property.
     * 
     * @return
     *     possible object is
     *     {@link QueueStore }
     *     
     */
    public QueueStore getQueueStore() {
        return queueStore;
    }

    /**
     * Sets the value of the queueStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueueStore }
     *     
     */
    public void setQueueStore(QueueStore value) {
        this.queueStore = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        if (name == null) {
            return "default";
        } else {
            return name;
        }
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="item-listener" type="{http://www.hazelcast.com/schema/config}item-listener" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "itemListener"
    })
    public static class ItemListeners {

        @XmlElement(name = "item-listener")
        protected List<ItemListener> itemListener;

        /**
         * Gets the value of the itemListener property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the itemListener property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItemListener().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ItemListener }
         * 
         * 
         */
        public List<ItemListener> getItemListener() {
            if (itemListener == null) {
                itemListener = new ArrayList<ItemListener>();
            }
            return this.itemListener;
        }

    }

}
