//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 A replicated map is a fully vector clock based, eventually consistent implementation of the map
 *                 interface. In difference to all other Hazelcast data structures this implementation is not
 *                 partitioned but fully replicates all data to all members.
 *                 Due to the nature of eventually consistency there is a chance of reading staled data and no
 *                 guarantee is given to retrieve the same value on multiple get calls.
 *                 ReplicatedMap was added in Hazelcast 3.2.
 *             
 * 
 * <p>Java class for replicatedmap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="replicatedmap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="in-memory-format" type="{http://www.hazelcast.com/schema/config}in-memory-format" minOccurs="0"/>
 *         &lt;element name="concurrency-level" type="{http://www.hazelcast.com/schema/config}concurrency-level" minOccurs="0"/>
 *         &lt;element name="replication-delay-millis" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="async-fillup" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="statistics-enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="entry-listeners" type="{http://www.hazelcast.com/schema/config}entry-listeners" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "replicatedmap", propOrder = {
    "inMemoryFormat",
    "concurrencyLevel",
    "replicationDelayMillis",
    "asyncFillup",
    "statisticsEnabled",
    "entryListeners"
})
public class Replicatedmap {

    @XmlElement(name = "in-memory-format", defaultValue = "OBJECT")
    @XmlSchemaType(name = "string")
    protected InMemoryFormat inMemoryFormat;
    @XmlElement(name = "concurrency-level", defaultValue = "32")
    protected Integer concurrencyLevel;
    @XmlElement(name = "replication-delay-millis", defaultValue = "100")
    @XmlSchemaType(name = "unsignedInt")
    protected Long replicationDelayMillis;
    @XmlElement(name = "async-fillup", defaultValue = "true")
    protected Boolean asyncFillup;
    @XmlElement(name = "statistics-enabled", defaultValue = "true")
    protected Boolean statisticsEnabled;
    @XmlElement(name = "entry-listeners")
    protected EntryListeners entryListeners;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the inMemoryFormat property.
     * 
     * @return
     *     possible object is
     *     {@link InMemoryFormat }
     *     
     */
    public InMemoryFormat getInMemoryFormat() {
        return inMemoryFormat;
    }

    /**
     * Sets the value of the inMemoryFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link InMemoryFormat }
     *     
     */
    public void setInMemoryFormat(InMemoryFormat value) {
        this.inMemoryFormat = value;
    }

    /**
     * Gets the value of the concurrencyLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getConcurrencyLevel() {
        return concurrencyLevel;
    }

    /**
     * Sets the value of the concurrencyLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setConcurrencyLevel(Integer value) {
        this.concurrencyLevel = value;
    }

    /**
     * Gets the value of the replicationDelayMillis property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getReplicationDelayMillis() {
        return replicationDelayMillis;
    }

    /**
     * Sets the value of the replicationDelayMillis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setReplicationDelayMillis(Long value) {
        this.replicationDelayMillis = value;
    }

    /**
     * Gets the value of the asyncFillup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAsyncFillup() {
        return asyncFillup;
    }

    /**
     * Sets the value of the asyncFillup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAsyncFillup(Boolean value) {
        this.asyncFillup = value;
    }

    /**
     * Gets the value of the statisticsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStatisticsEnabled() {
        return statisticsEnabled;
    }

    /**
     * Sets the value of the statisticsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStatisticsEnabled(Boolean value) {
        this.statisticsEnabled = value;
    }

    /**
     * Gets the value of the entryListeners property.
     * 
     * @return
     *     possible object is
     *     {@link EntryListeners }
     *     
     */
    public EntryListeners getEntryListeners() {
        return entryListeners;
    }

    /**
     * Sets the value of the entryListeners property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntryListeners }
     *     
     */
    public void setEntryListeners(EntryListeners value) {
        this.entryListeners = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
