//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for security complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="security">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="member-credentials-factory" type="{http://www.hazelcast.com/schema/config}security-object" minOccurs="0"/>
 *         &lt;element name="member-login-modules" type="{http://www.hazelcast.com/schema/config}login-modules" minOccurs="0"/>
 *         &lt;element name="client-login-modules" type="{http://www.hazelcast.com/schema/config}login-modules" minOccurs="0"/>
 *         &lt;element name="client-permission-policy" type="{http://www.hazelcast.com/schema/config}security-object" minOccurs="0"/>
 *         &lt;element name="client-permissions" type="{http://www.hazelcast.com/schema/config}permissions" minOccurs="0"/>
 *         &lt;element name="security-interceptors" type="{http://www.hazelcast.com/schema/config}interceptors" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "security", propOrder = {
    "memberCredentialsFactory",
    "memberLoginModules",
    "clientLoginModules",
    "clientPermissionPolicy",
    "clientPermissions",
    "securityInterceptors"
})
public class Security {

    @XmlElement(name = "member-credentials-factory")
    protected SecurityObject memberCredentialsFactory;
    @XmlElement(name = "member-login-modules")
    protected LoginModules memberLoginModules;
    @XmlElement(name = "client-login-modules")
    protected LoginModules clientLoginModules;
    @XmlElement(name = "client-permission-policy")
    protected SecurityObject clientPermissionPolicy;
    @XmlElement(name = "client-permissions")
    protected Permissions clientPermissions;
    @XmlElement(name = "security-interceptors")
    protected Interceptors securityInterceptors;
    @XmlAttribute(name = "enabled")
    protected Boolean enabled;

    /**
     * Gets the value of the memberCredentialsFactory property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityObject }
     *     
     */
    public SecurityObject getMemberCredentialsFactory() {
        return memberCredentialsFactory;
    }

    /**
     * Sets the value of the memberCredentialsFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityObject }
     *     
     */
    public void setMemberCredentialsFactory(SecurityObject value) {
        this.memberCredentialsFactory = value;
    }

    /**
     * Gets the value of the memberLoginModules property.
     * 
     * @return
     *     possible object is
     *     {@link LoginModules }
     *     
     */
    public LoginModules getMemberLoginModules() {
        return memberLoginModules;
    }

    /**
     * Sets the value of the memberLoginModules property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoginModules }
     *     
     */
    public void setMemberLoginModules(LoginModules value) {
        this.memberLoginModules = value;
    }

    /**
     * Gets the value of the clientLoginModules property.
     * 
     * @return
     *     possible object is
     *     {@link LoginModules }
     *     
     */
    public LoginModules getClientLoginModules() {
        return clientLoginModules;
    }

    /**
     * Sets the value of the clientLoginModules property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoginModules }
     *     
     */
    public void setClientLoginModules(LoginModules value) {
        this.clientLoginModules = value;
    }

    /**
     * Gets the value of the clientPermissionPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityObject }
     *     
     */
    public SecurityObject getClientPermissionPolicy() {
        return clientPermissionPolicy;
    }

    /**
     * Sets the value of the clientPermissionPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityObject }
     *     
     */
    public void setClientPermissionPolicy(SecurityObject value) {
        this.clientPermissionPolicy = value;
    }

    /**
     * Gets the value of the clientPermissions property.
     * 
     * @return
     *     possible object is
     *     {@link Permissions }
     *     
     */
    public Permissions getClientPermissions() {
        return clientPermissions;
    }

    /**
     * Sets the value of the clientPermissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Permissions }
     *     
     */
    public void setClientPermissions(Permissions value) {
        this.clientPermissions = value;
    }

    /**
     * Gets the value of the securityInterceptors property.
     * 
     * @return
     *     possible object is
     *     {@link Interceptors }
     *     
     */
    public Interceptors getSecurityInterceptors() {
        return securityInterceptors;
    }

    /**
     * Sets the value of the securityInterceptors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interceptors }
     *     
     */
    public void setSecurityInterceptors(Interceptors value) {
        this.securityInterceptors = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEnabled() {
        if (enabled == null) {
            return false;
        } else {
            return enabled;
        }
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnabled(Boolean value) {
        this.enabled = value;
    }

}
