//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for serialization complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="serialization">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="portable-version" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="use-native-byte-order" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="byte-order" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.hazelcast.com/schema/config}non-space-string">
 *               &lt;enumeration value="BIG_ENDIAN"/>
 *               &lt;enumeration value="LITTLE_ENDIAN"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="enable-compression" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="enable-shared-object" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="allow-unsafe" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="data-serializable-factories" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="data-serializable-factory" type="{http://www.hazelcast.com/schema/config}serialization-factory" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="portable-factories" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="portable-factory" type="{http://www.hazelcast.com/schema/config}serialization-factory" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="serializers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="global-serializer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="serializer" type="{http://www.hazelcast.com/schema/config}serializer" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="check-class-def-errors" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "serialization", propOrder = {
    "portableVersion",
    "useNativeByteOrder",
    "byteOrder",
    "enableCompression",
    "enableSharedObject",
    "allowUnsafe",
    "dataSerializableFactories",
    "portableFactories",
    "serializers",
    "checkClassDefErrors"
})
public class Serialization {

    @XmlElement(name = "portable-version")
    @XmlSchemaType(name = "unsignedInt")
    protected Long portableVersion;
    @XmlElement(name = "use-native-byte-order", defaultValue = "false")
    protected Boolean useNativeByteOrder;
    @XmlElement(name = "byte-order", defaultValue = "BIG_ENDIAN")
    protected String byteOrder;
    @XmlElement(name = "enable-compression", defaultValue = "false")
    protected Boolean enableCompression;
    @XmlElement(name = "enable-shared-object", defaultValue = "false")
    protected Boolean enableSharedObject;
    @XmlElement(name = "allow-unsafe", defaultValue = "false")
    protected Boolean allowUnsafe;
    @XmlElement(name = "data-serializable-factories")
    protected Serialization.DataSerializableFactories dataSerializableFactories;
    @XmlElement(name = "portable-factories")
    protected Serialization.PortableFactories portableFactories;
    protected Serialization.Serializers serializers;
    @XmlElement(name = "check-class-def-errors", defaultValue = "true")
    protected Boolean checkClassDefErrors;

    /**
     * Gets the value of the portableVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPortableVersion() {
        return portableVersion;
    }

    /**
     * Sets the value of the portableVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPortableVersion(Long value) {
        this.portableVersion = value;
    }

    /**
     * Gets the value of the useNativeByteOrder property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseNativeByteOrder() {
        return useNativeByteOrder;
    }

    /**
     * Sets the value of the useNativeByteOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseNativeByteOrder(Boolean value) {
        this.useNativeByteOrder = value;
    }

    /**
     * Gets the value of the byteOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getByteOrder() {
        return byteOrder;
    }

    /**
     * Sets the value of the byteOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setByteOrder(String value) {
        this.byteOrder = value;
    }

    /**
     * Gets the value of the enableCompression property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableCompression() {
        return enableCompression;
    }

    /**
     * Sets the value of the enableCompression property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableCompression(Boolean value) {
        this.enableCompression = value;
    }

    /**
     * Gets the value of the enableSharedObject property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableSharedObject() {
        return enableSharedObject;
    }

    /**
     * Sets the value of the enableSharedObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableSharedObject(Boolean value) {
        this.enableSharedObject = value;
    }

    /**
     * Gets the value of the allowUnsafe property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowUnsafe() {
        return allowUnsafe;
    }

    /**
     * Sets the value of the allowUnsafe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowUnsafe(Boolean value) {
        this.allowUnsafe = value;
    }

    /**
     * Gets the value of the dataSerializableFactories property.
     * 
     * @return
     *     possible object is
     *     {@link Serialization.DataSerializableFactories }
     *     
     */
    public Serialization.DataSerializableFactories getDataSerializableFactories() {
        return dataSerializableFactories;
    }

    /**
     * Sets the value of the dataSerializableFactories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Serialization.DataSerializableFactories }
     *     
     */
    public void setDataSerializableFactories(Serialization.DataSerializableFactories value) {
        this.dataSerializableFactories = value;
    }

    /**
     * Gets the value of the portableFactories property.
     * 
     * @return
     *     possible object is
     *     {@link Serialization.PortableFactories }
     *     
     */
    public Serialization.PortableFactories getPortableFactories() {
        return portableFactories;
    }

    /**
     * Sets the value of the portableFactories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Serialization.PortableFactories }
     *     
     */
    public void setPortableFactories(Serialization.PortableFactories value) {
        this.portableFactories = value;
    }

    /**
     * Gets the value of the serializers property.
     * 
     * @return
     *     possible object is
     *     {@link Serialization.Serializers }
     *     
     */
    public Serialization.Serializers getSerializers() {
        return serializers;
    }

    /**
     * Sets the value of the serializers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Serialization.Serializers }
     *     
     */
    public void setSerializers(Serialization.Serializers value) {
        this.serializers = value;
    }

    /**
     * Gets the value of the checkClassDefErrors property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCheckClassDefErrors() {
        return checkClassDefErrors;
    }

    /**
     * Sets the value of the checkClassDefErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCheckClassDefErrors(Boolean value) {
        this.checkClassDefErrors = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="data-serializable-factory" type="{http://www.hazelcast.com/schema/config}serialization-factory" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataSerializableFactory"
    })
    public static class DataSerializableFactories {

        @XmlElement(name = "data-serializable-factory")
        protected List<SerializationFactory> dataSerializableFactory;

        /**
         * Gets the value of the dataSerializableFactory property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dataSerializableFactory property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDataSerializableFactory().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SerializationFactory }
         * 
         * 
         */
        public List<SerializationFactory> getDataSerializableFactory() {
            if (dataSerializableFactory == null) {
                dataSerializableFactory = new ArrayList<SerializationFactory>();
            }
            return this.dataSerializableFactory;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="portable-factory" type="{http://www.hazelcast.com/schema/config}serialization-factory" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "portableFactory"
    })
    public static class PortableFactories {

        @XmlElement(name = "portable-factory")
        protected List<SerializationFactory> portableFactory;

        /**
         * Gets the value of the portableFactory property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the portableFactory property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPortableFactory().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SerializationFactory }
         * 
         * 
         */
        public List<SerializationFactory> getPortableFactory() {
            if (portableFactory == null) {
                portableFactory = new ArrayList<SerializationFactory>();
            }
            return this.portableFactory;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="global-serializer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="serializer" type="{http://www.hazelcast.com/schema/config}serializer" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "globalSerializer",
        "serializer"
    })
    public static class Serializers {

        @XmlElement(name = "global-serializer")
        protected String globalSerializer;
        protected List<Serializer> serializer;

        /**
         * Gets the value of the globalSerializer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGlobalSerializer() {
            return globalSerializer;
        }

        /**
         * Sets the value of the globalSerializer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGlobalSerializer(String value) {
            this.globalSerializer = value;
        }

        /**
         * Gets the value of the serializer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the serializer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSerializer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Serializer }
         * 
         * 
         */
        public List<Serializer> getSerializer() {
            if (serializer == null) {
                serializer = new ArrayList<Serializer>();
            }
            return this.serializer;
        }

    }

}
