//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for target-cluster complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="target-cluster">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="replication-impl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="end-points" type="{http://www.hazelcast.com/schema/config}end-points"/>
 *       &lt;/sequence>
 *       &lt;attribute name="group-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="group-password" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "target-cluster", propOrder = {
    "replicationImpl",
    "endPoints"
})
public class TargetCluster {

    @XmlElement(name = "replication-impl", required = true)
    protected String replicationImpl;
    @XmlElement(name = "end-points", required = true)
    protected EndPoints endPoints;
    @XmlAttribute(name = "group-name", required = true)
    protected String groupName;
    @XmlAttribute(name = "group-password", required = true)
    protected String groupPassword;

    /**
     * Gets the value of the replicationImpl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplicationImpl() {
        return replicationImpl;
    }

    /**
     * Sets the value of the replicationImpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplicationImpl(String value) {
        this.replicationImpl = value;
    }

    /**
     * Gets the value of the endPoints property.
     * 
     * @return
     *     possible object is
     *     {@link EndPoints }
     *     
     */
    public EndPoints getEndPoints() {
        return endPoints;
    }

    /**
     * Sets the value of the endPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndPoints }
     *     
     */
    public void setEndPoints(EndPoints value) {
        this.endPoints = value;
    }

    /**
     * Gets the value of the groupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupName(String value) {
        this.groupName = value;
    }

    /**
     * Gets the value of the groupPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupPassword() {
        return groupPassword;
    }

    /**
     * Sets the value of the groupPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupPassword(String value) {
        this.groupPassword = value;
    }

}
