//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.22 at 07:46:10 PM IST 
//


package cloud.configs.hazelcast.dynamictemplate.v34.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for topology-changed-strategy.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="topology-changed-strategy">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CANCEL_RUNNING_OPERATION"/>
 *     &lt;enumeration value="DISCARD_AND_RESTART"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "topology-changed-strategy")
@XmlEnum
public enum TopologyChangedStrategy {

    CANCEL_RUNNING_OPERATION,
    DISCARD_AND_RESTART;

    public String value() {
        return name();
    }

    public static TopologyChangedStrategy fromValue(String v) {
        return valueOf(v);
    }

}
